### ISSUE TITLE
Charset problem

### ISSUE THREAD

**Issue by netkrd** [Techtronix/censor-generator#1]
Hello charset problem
Eg:
<badword text="sÃ¼mik" replace="test">

ÇûêüÜşğöîâ proglem how can I fix

**Comment by Techman** [comment]
Huh?

**Comment by netkrd** [comment]
as

```
<badword text="AzsÄ±z" replace="Test">
Ä± = ı
<badword text="aÄzinc" replace="Test">
Ä = ğ
<badword text="Ã§vyim" replace="Test">
Ã§ = ç

```

Charset problem

**Comment by Techman** [comment]
I'm sorry, but I honestly have no idea what is going on here. I am not sure if this is even a problem with the script.

All this project does is take in a word list and spit out a config file for convenience.

If you believe there is a problem with the script, please provide additional information so I can try and reproduce the issue. If this is a problem with InspIRCd itself, you are better off asking for support on their IRC channel or filing an issue in their repo.

**Comment by Techman** [comment]
I am going to close this now since it has been a week with no response.
